-- Users table
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('admin', 'user', 'readonly')),
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Medical sessions table
CREATE TABLE IF NOT EXISTS medical_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    video_s3_key TEXT,
    video_original_name TEXT,
    video_duration_seconds INTEGER,
    video_size_bytes INTEGER,
    video_mime_type TEXT,
    language TEXT DEFAULT 'es', -- ISO 639-1 code (auto-detected from audio)
    summary TEXT,
    keywords TEXT, -- JSON array
    user_tags TEXT, -- JSON array
    notes TEXT,
    error_message TEXT,
    is_simulated INTEGER DEFAULT 0, -- 1 if session was generated by simulator
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    started_at TEXT, -- When processing started (first job)
    completed_at TEXT,
    processing_cost_usd REAL, -- Total processing cost in USD
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_medical_sessions_user_id ON medical_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_medical_sessions_status ON medical_sessions(status);
CREATE INDEX IF NOT EXISTS idx_medical_sessions_created_at ON medical_sessions(created_at);

-- Transcript sections table
CREATE TABLE IF NOT EXISTS transcript_sections (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    section_type TEXT NOT NULL,
    section_order INTEGER NOT NULL,
    speaker TEXT,
    content TEXT NOT NULL,
    start_time_seconds REAL,
    end_time_seconds REAL,
    created_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (session_id) REFERENCES medical_sessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_transcript_sections_session_id ON transcript_sections(session_id);
CREATE INDEX IF NOT EXISTS idx_transcript_sections_section_type ON transcript_sections(section_type);

-- Section summaries table (one summary per section type per session)
CREATE TABLE IF NOT EXISTS section_summaries (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    section_type TEXT NOT NULL,
    summary TEXT NOT NULL,
    created_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (session_id) REFERENCES medical_sessions(id) ON DELETE CASCADE,
    UNIQUE(session_id, section_type)
);

CREATE INDEX IF NOT EXISTS idx_section_summaries_session_id ON section_summaries(session_id);

-- Processing jobs table
CREATE TABLE IF NOT EXISTS processing_jobs (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    job_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    priority INTEGER DEFAULT 0,
    attempts INTEGER DEFAULT 0,
    max_attempts INTEGER DEFAULT 3,
    error_message TEXT,
    started_at TEXT,
    completed_at TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    input_tokens INTEGER,
    output_tokens INTEGER,
    audio_duration_seconds INTEGER, -- Only for transcription jobs
    cost_usd REAL,
    FOREIGN KEY (session_id) REFERENCES medical_sessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_processing_jobs_status ON processing_jobs(status);
CREATE INDEX IF NOT EXISTS idx_processing_jobs_session_id ON processing_jobs(session_id);

-- Clinical indicators table (one per session)
CREATE TABLE IF NOT EXISTS clinical_indicators (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL UNIQUE,
    urgency_level TEXT CHECK(urgency_level IN ('low', 'medium', 'high')),
    appointment_priority TEXT CHECK(appointment_priority IN ('preferred', 'non_preferred')),
    reason_for_visit TEXT,
    consulted_specialty TEXT,
    main_clinical_problem TEXT,
    problem_status TEXT CHECK(problem_status IN ('new', 'chronic', 'exacerbation', 'follow_up', 'resolved')),
    diagnostic_hypothesis TEXT, -- JSON array: [{condition, certainty}]
    requested_tests TEXT,       -- JSON array: string[]
    treatment_plan TEXT,        -- JSON object: {medication_started, medication_adjusted, medication_discontinued, non_pharmacological_measures}
    patient_education TEXT,     -- JSON array: string[]
    warning_signs TEXT,         -- JSON array: string[]
    follow_up_plan TEXT,        -- JSON object: {follow_up_type, time_frame, responsible_care_level}
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (session_id) REFERENCES medical_sessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_clinical_indicators_session_id ON clinical_indicators(session_id);
CREATE INDEX IF NOT EXISTS idx_clinical_indicators_urgency ON clinical_indicators(urgency_level);
CREATE INDEX IF NOT EXISTS idx_clinical_indicators_problem_status ON clinical_indicators(problem_status);

-- Simulations table (for tracking simulator progress)
CREATE TABLE IF NOT EXISTS simulations (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    current_step TEXT,
    total_segments INTEGER,
    completed_segments INTEGER DEFAULT 0,
    context TEXT NOT NULL,
    language TEXT NOT NULL,
    voices TEXT NOT NULL, -- JSON object: {DOCTOR: voiceId, PATIENT: voiceId, SPECIALIST: voiceId}
    title TEXT,
    user_tags TEXT, -- JSON array
    notes TEXT,
    session_id TEXT,
    error_message TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    completed_at TEXT, -- When simulation finished
    conversation_started_at TEXT,
    conversation_completed_at TEXT,
    audio_started_at TEXT,
    audio_completed_at TEXT,
    concatenation_started_at TEXT,
    concatenation_completed_at TEXT,
    conversation_input_tokens INTEGER,
    conversation_output_tokens INTEGER,
    conversation_cost_usd REAL,
    elevenlabs_characters INTEGER,
    elevenlabs_cost_usd REAL,
    total_cost_usd REAL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES medical_sessions(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_simulations_user_id ON simulations(user_id);
CREATE INDEX IF NOT EXISTS idx_simulations_status ON simulations(status);

-- Session assignments table (many-to-many: sessions can be assigned to multiple users)
CREATE TABLE IF NOT EXISTS session_assignments (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    can_write INTEGER NOT NULL DEFAULT 0,  -- 0 = read-only, 1 = can modify
    assigned_by TEXT NOT NULL,
    assigned_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (session_id) REFERENCES medical_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE(session_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_session_assignments_session_id ON session_assignments(session_id);
CREATE INDEX IF NOT EXISTS idx_session_assignments_user_id ON session_assignments(user_id);

-- Consultation summaries table (one per session, stores AI-generated patient-friendly summaries)
CREATE TABLE IF NOT EXISTS consultation_summaries (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL UNIQUE,
    what_happened TEXT NOT NULL,
    diagnosis TEXT NOT NULL,
    treatment_plan TEXT NOT NULL,
    follow_up TEXT NOT NULL,
    warning_signs TEXT NOT NULL,
    additional_notes TEXT,
    tooltips TEXT,
    share_token TEXT UNIQUE,
    share_expires_at TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (session_id) REFERENCES medical_sessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_consultation_summaries_session_id ON consultation_summaries(session_id);
CREATE INDEX IF NOT EXISTS idx_consultation_summaries_share_token ON consultation_summaries(share_token);

-- Report summaries table (standalone doctor report → AI patient-friendly summary)
CREATE TABLE IF NOT EXISTS report_summaries (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT,
    what_happened TEXT NOT NULL,
    diagnosis TEXT NOT NULL,
    treatment_plan TEXT NOT NULL,
    follow_up TEXT NOT NULL,
    warning_signs TEXT NOT NULL,
    additional_notes TEXT,
    tooltips TEXT,
    share_token TEXT UNIQUE,
    share_expires_at TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_report_summaries_user_id ON report_summaries(user_id);
CREATE INDEX IF NOT EXISTS idx_report_summaries_share_token ON report_summaries(share_token);

-- FTS5 virtual table for full-text search on transcripts
CREATE VIRTUAL TABLE IF NOT EXISTS transcript_fts USING fts5(
    session_id,
    content,
    tokenize='porter unicode61'
);

-- Triggers to keep FTS in sync
CREATE TRIGGER IF NOT EXISTS transcript_sections_ai AFTER INSERT ON transcript_sections BEGIN
    INSERT INTO transcript_fts(session_id, content) VALUES (NEW.session_id, NEW.content);
END;

CREATE TRIGGER IF NOT EXISTS transcript_sections_ad AFTER DELETE ON transcript_sections BEGIN
    DELETE FROM transcript_fts WHERE session_id = OLD.session_id AND content = OLD.content;
END;

CREATE TRIGGER IF NOT EXISTS transcript_sections_au AFTER UPDATE ON transcript_sections BEGIN
    DELETE FROM transcript_fts WHERE session_id = OLD.session_id AND content = OLD.content;
    INSERT INTO transcript_fts(session_id, content) VALUES (NEW.session_id, NEW.content);
END;
